<?php
/**
 * wallee Magento 2
 *
 * This Magento 2 extension enables to process payments with wallee (https://www.wallee.com).
 *
 * @package Wallee_Payment
 * @author wallee AG (https://www.wallee.com)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)

 */
/**
 * @formatter:off
 */

/** @var $block \Wallee\Payment\Block\Method\Info */
?>

<div class="admin__page-section-item-content">
    <table class="data-table admin__table-secondary">
        <tr>
            <th><?=$escaper->escapeHtml(\__('Payment Method'))?></th>
            <td>
                <?=$escaper->escapeHtml($block->getMethod()->getPaymentMethodConfiguration()->getConfigurationName()) ?>
            </td>
        </tr>
        <?php $imageUrl = $block->getImageUrl(); if ($imageUrl): ?>
            <tr>
                <th></th>
                <td><img src="<?=$escaper->escapeHtml($imageUrl)?>" width="50" /></td>
            </tr>
        <?php endif; ?>
        <?php if ($block->getTransaction()): ?>
            <tr>
                <th><?=$escaper->escapeHtml(\__('Transaction State'))?></th>
                <td><?=$escaper->escapeHtml($block->getTransactionState()) ?></td>
            </tr>
            <?php if ($block->getTransaction()->getFailureReason() != null): ?>
                <tr>
                    <th><?=$escaper->escapeHtml(\__('Failure Reason'))?></th>
                    <td><?=$escaper->escapeHtml($block->translate($block->getTransaction()->getFailureReason())) ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <th><?=$escaper->escapeHtml(\__('Authorization Amount'))?></th>
                <td>
                    <?=$escaper->escapeHtml($block->formatAmount($block->getTransaction()->getAuthorizationAmount())) ?>
                </td>
            </tr>
            <tr>
                <th><?=$escaper->escapeHtml(\__('Transaction'))?></th>
                <td>
                    <a target="_blank" href="<?=$escaper->escapeHtml($block->getTransactionUrl())?>">
                        <?=$escaper->escapeHtml(\__('View in wallee'))?>
                    </a>
                </td>
            </tr>
            <tr>
                <th><?=$escaper->escapeHtml(\__('Customer'))?></th>
                <td>
                    <a target="_blank" href="<?=$escaper->escapeHtml($block->getCustomerUrl())?>">
                        <?=$escaper->escapeHtml(\__('View in wallee'))?>
                    </a>
                </td>
            </tr>
        <?php endif; ?>
        <?php if ($block->isInvoice() && $block->isInvoiceDownloadAllowed()): ?>
            <tr>
                <th><?=$escaper->escapeHtml(\__('Invoice'))?></th>
                <td>
                    <a href="<?=$escaper->escapeHtml($block->getInvoiceDownloadUrl())?>">
                        <?=$escaper->escapeHtml(\__('Download Invoice'))?>
                    </a>
                </td>
            </tr>
        <?php endif;?>
        <?php if ($block->isShipment() && $block->isPackingSlipDownloadAllowed()): ?>
            <tr>
                <th><?=$escaper->escapeHtml(\__('Packing Slip'))?></th>
                <td>
                    <a href="<?=$escaper->escapeHtml($block->getPackingSlipDownloadUrl())?>">
                        <?=$escaper->escapeHtml(\__('Download Packing Slip'))?>
                    </a>
                </td>
            </tr>
        <?php endif;?>
        <?php if ($block->isCreditmemo() && $block->isRefundDownloadAllowed()): ?>
            <tr>
                <th><?=$escaper->escapeHtml(\__('Refund'))?></th>
                <td>
                    <a href="<?=$escaper->escapeHtml($block->getRefundDownloadUrl())?>">
                        <?=$escaper->escapeHtml(\__('Download Refund'))?>
                    </a>
                </td>
            </tr>
        <?php endif;?>
    </table>

    <?php foreach ($block->getGroupedLabels() as $group): ?>
        <div class="wallee-label-container">
            <a><?=$escaper->escapeHtml($block->translate($group->getName()))?></a>
            <table class="data-table admin__table-secondary">
                <?php foreach ($group->getLabels() as $label): ?>
                    <tr>
                        <th><?=$escaper->escapeHtml($block->translate($label->getName()))?></th>
                        <td><?=$escaper->escapeHtml($label->getValue()) ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endforeach; ?>
</div>